config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: 'users#index'
  # resources :users do
  #   resources :posts
  # end
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[new create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  def update_comment_counter
    post.increment!(:commentsCounter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  def update_like_counter
    post.increment!(:likesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  attribute :commentsCounter, :integer, default: 0
  attribute :likesCounter, :integer, default: 0

  def update_post_counter
    author.increment!(:postsCounter)
  end

  def recent_five_comments()
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  attribute :postsCounter, :integer, default: 0

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   # def current_user
#   #   User.first
#   # end
# end
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @current_user = current_user
    @new_comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @new_comment = Comment.create(comment_params)
    @new_comment.author = current_user
    @new_comment.post = @post

    if @new_comment.save
      @new_comment.update_comment_counter
      redirect_to user_post_path(current_user.id, @post.id)
    else
      render :new, alert: 'error'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @new_like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @new_like = Like.new
    @new_like.author = @user
    @new_like.post = @post

    if @new_like.save
      @new_like.update_like_counter
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id),
                  alert: 'error'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
    @likes = @post.likes
  end

  def new
    @current_user = current_user
    @new_post = Post.new
  end

  def create
    @new_post = Post.new(post_params)
    @new_post.author = current_user

    if @new_post.save
      @new_post.update_post_counter
      flash[:notice] = 'successfully post.'
      redirect_to user_path(@new_post.author_id), notice: 'Post successfully'
    else
      render :new, alert: 'error'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Add New Comment</h1>
<%= form_with model: @new_comment, url: user_post_comments_path  do |form|  %>
  <div class="wows">
    <%= form.label :Comment ,class: "formlabel" %>
    <%= form.text_area :text ,class: "form" %>
  </div>
  <%= form.submit "Add comment" ,class: "btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'style' %>

  </head>

  <body>
  <% if user_signed_in? %>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<% else %>
         <%= link_to "Sign In", new_user_session_path, method: :delete %>
         <%= link_to "Sign Up", new_user_registration_path, method: :delete %>
 <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
<div><div class="aside">
    <div class="aside__left">
    <div class="aside__left__responsive">
    <img src= <%=  @user.photo %> alt= <%=  @user.id %> class="responsive aside__left__responsive__respo">
    </div>
    </div>
    <div class="aside__right">
    <%=  @user.name %>
    <%=  @user.postsCounter || 0 %>
    <%= link_to "Add post", new_user_post_path(@user.id), class: "wow"  %>
    </div>
    </div></div>
</div>

<ul class="useridposts">
  <% @posts.each do |post| %>
<div class="container">
    <li class="postshow">
    <span>  <%= post.id %> #</span>
   <span> <%= link_to post.title, user_post_path(@user, post) %></span>
   <span> <%=  post.text %></span>
    <span> comments:  <%=  post.commentsCounter || 0 %> </span>
    <span> likes: <%=  post.likesCounter || 0 %> </span>


<div class="postcomment">
 <% post.recent_five_comments.each do |comment|%>
          <p class="commentee"><%= comment.author.name %> : <%= comment.text %></p>
        <% end %>
</div>

    </li>
</div>
  <% end %>
  </ul>

app/views/posts/new.html.erb
<section class="wsr">
  <h1>New post</h1>
  <% if @new_post.errors.any? %>
    <div class="daa">
      <% @new_post.errors.full_messages.each do |message| %>
        <div> <%= message %></div>
      <% end %>
    </div>
  <% end %>
  <%= form_with model: @new_post, url: user_posts_path(@current_user)  do |form|  %>
    <div class="wows">
      <%= form.label :title ,class: "form" %>
      <%= form.text_field :title ,class: "vcv" %>
    </div>
    <div class="wows">
      <%= form.label :text ,class: "formlabel" %>
      <%= form.text_area :text ,class: "area" %>
    </div>
    <%= form.submit "Add post" ,class: "btn" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<div class="container">
<div class="showpost">

<div class="flex"><span><%= @post.id %># By : <%= @user.name %>  </span> <span> comments:  <%=  @post.commentsCounter || 0 %> </span> <span> likes:  <%=  @post.likesCounter || 0 %> </span></div>
<p><%= @post.text %></p>
    <div class="sd">
      <%= form_with model: @new_like, url: user_post_likes_path(post_id: @post.id)  do |form|  %>
        <%= form.submit "Add like " ,class: "xd" %>
      <% end %>
      <%= link_to "Add comment ", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id ) %>
    </div>
  </div>
</div>
<div class="showpostcomment">
 <% @post.comments.each do |comment|%>
          <p><%= comment.author.name %> : <%= comment.text %></p>
        <% end %>
</div>
</div>

<p>Posted by <%= @user.name %> on <%= @post.created_at.strftime("%B %d, %Y") %></p>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
   <div class="container">
    <li><div class="aside">
    <div class="aside__left">
    <div class="aside__left__responsive">
    <img src= <%=  user.photo %> alt= <%=  user.id %> class="responsivee aside__left__responsive__respo" id="user-photo">
    </div>
    </div>
    <div class="aside__right">
    <%= link_to user.name, user_path(user) %>
    <%=  user.postsCounter || 0 %>
    </div>
    </div></li>
   </div>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="container">
<div><div class="aside">
    <div class="aside__left">
    <div class="aside__left__responsive">
    <img src= <%=  @user.photo %> alt= <%=  @user.id %> class="responsive aside__left__responsive__respo">
    </div>
    </div>
    <div class="aside__right">
    <%=  @user.name %>
    <%=  @user.postsCounter %>
    </div>
    </div></div>
<div class="bio">
<span>Bio</span><br>
 <%=  @user.bio %>
</div>
</div>

<h2>Posts:</h2>

<ul class="useridposts">
  <% @user.recent_posts.each do |post| %>
   <div class="container">
    <li>
    <span>  <%= post.id %> #</span>
   <span> <%= link_to post.title, user_post_path(@user, post), :class => 'post-title' %></span>
   <span> <%=  post.text %></span>
    <span> comments:  <%=  post.commentsCounter || 0 %> </span>
    <span> likes:  <%=  post.likesCounter || 0 %> </span>
 
    </li>
   </div>
  <% end %>
  <button class="seeallposts"><%= link_to "See all posts", user_posts_path(@user) %></button>

</ul>